### PR TITLE
WDP241101-12

### PR DESCRIPTION
**Pull request by NocnyZwierz**
I created the stickyBar component. It was styled and added logic that adds elements to the comparison.

https://projects.kodilla.com/browse/WDP241101-12

### CODE REVIEW

**Comment by kalipp1** [comment]
I don't know if it's only on my computer or others too, but when i click compare button of random each item my page refreshes and locates me to the top of my page.

**Comment by NocnyZwierz** [comment]
@matwjablonski Should i change the button component or leave it as it is for now?

**Comment by matwjablonski** [comment]
Zrzut ekranu 2024-11-26 o 20 50 23

something is not working ;)

**Review by kalipp1 — APPROVED** [review]
Now it works great. Well done !!

**Review by kalipp1 — DISMISSED** [review]

**Review by kalipp1 — APPROVED** [review]
Good job!

**Review by matwjablonski — APPROVED** [review]

**Pull request merged**
